### ISSUE TITLE
Publish new version on atmosphere compatible with Meteor 1.6.1

### ISSUE THREAD

**Issue by SimonSimCity** [Urigo/meteor-static-html-compiler#23]
@sebakerckhof, @Urigo I've seen that you added the changes necessary to make this package compatible with Meteor 1.6.1 in https://github.com/Urigo/meteor-static-html-compiler/pull/22. Could you now also publish a new version on `atmosphere` so we can update to it without having to include the package in our project?

**Comment by SimonSimCity** [comment]
~Maybe it's also a good idea to take it back from version `1.0.0` to a lower version, because now you'll have to republish all the packages dependent on it.~

**Comment by SimonSimCity** [comment]
There are a lot of packages dependent on this one, but I've now chosen to create a PR for one of them (see https://github.com/Urigo/meteor-static-templates/pull/19) which requires this package in version `1.0.0`. Please publish it soon, or give me access and I can publish it ...

**Comment by sebakerckhof** [comment]
1.0.0 has been released.

**Comment by sebakerckhof** [comment]
@SimonSimCity, looks like there's a problem with the meteor publish of the package: https://github.com/meteor/meteor/issues/9738 . So for the time being you'll have to keep it included locally.

**Comment by sebakerckhof** [comment]
Was able to workaround the issue for now and released as v `1.0.0_2`
